service: pepe

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-resource-tagging

custom:
  wsgi:
    app: src/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-1
  environment:
    GLOBAL_IPSET: 8be5af6e-3f1f-4a57-a8bf-2bcacdb06a5a
    REGIONAL_IPSET: 452b9455-9696-42cd-95a5-c77b5ff4fead
  stackTags:
    environment: tools
    duration: temporary

functions:
  pepe:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
