service: pepe

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-resource-tagging

package:
  exclude:
    - ./**
    - '!src/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  timemout: 15
  role: ${env:ROLE}
  environment:
    HUND_WEBHOOK: ${env:HUND_WEBHOOK}
    AWS_WEBHOOK: ${env:AWS_WEBHOOK}
    AUDIENCE: ${env:AUDIENCE}
    USERS: ${env:USERS}
    DEV_SGID: ${env:DEV_SGID}
    QA_SGID: ${env:QA_SGID}
    PROD_SGID: ${env:PROD_SGID}
    TOOLS_SGID: ${env:TOOLS_SGID}
    GLOBAL_IPSET_DYNAMIC: ${env:GLOBAL_IPSET_DYNAMIC}
    GLOBAL_IPSET_FIXED: ${env:GLOBAL_IPSET_FIXED}
    REGIONAL_IPSET_DYNAMIC: ${env:REGIONAL_IPSET_DYNAMIC}
    REGIONAL_IPSET_FIXED: ${env:REGIONAL_IPSET_FIXED}
  stackTags:
    environment: tools
    duration: indeterminate
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  pepe:
    handler: src/app.handler
    name: ${env:STAGE}-pepe-bot
    events:
      - http:
          method: POST
          path: googlechat
      - http:
          method: POST
          path: hundio
      - cloudwatchLog:
          logGroup: /ecs/dev-fineract-api
          filter: org.apache.fineract.infrastructure.jobs.exception.JobExecutionException
