service: pepe

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-resource-tagging

package:
  exclude:
    - ./**
    - '!src/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  timemout: 15
  role: ${env:ROLE}
  environment:
    HUND_WEBHOOK: ${env:HUND_WEBHOOK}
    AWS_WEBHOOK: ${env:AWS_WEBHOOK}
    AUDIENCE: ${env:AUDIENCE}
    USERS: ${env:USERS}
    DEV_SGID: ${env:DEV_SGID}
    QA_SGID: ${env:QA_SGID}
    PROD_SGID: ${env:PROD_SGID}
    TOOLS_SGID: ${env:TOOLS_SGID}
    GLOBAL_IPSET_DYNAMIC: ${env:GLOBAL_IPSET_DYNAMIC}
    GLOBAL_IPSET_FIXED: ${env:GLOBAL_IPSET_FIXED}
    REGIONAL_IPSET_DYNAMIC: ${env:REGIONAL_IPSET_DYNAMIC}
    REGIONAL_IPSET_FIXED: ${env:REGIONAL_IPSET_FIXED}
  stackTags:
    environment: tools
    duration: indeterminate
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  pepe:
    handler: src/app.handler
    name: ${self:provider.stage}-pepe-bot
    events:
      - http:
          method: POST
          path: googlechat
      - schedule:
        name: clear-waf-dynamic-ips
        description: Clear  all waf dynamic ips
        rate: cron(0 9 ? */2 MON *)
        input:
          resource: cloudwatch events
          user:
            displayName: DevOps
            email: devops@boomcredit.net
          message:
            argumentText: clean
            annotations:
              - slashCommand:
                commandName: '/iprelease'
            slashCommand:
              commandId: 1
