service: pepe

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-resource-tagging

package:
  patterns:
    - '!./**'
    - 'src/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  timeout: 15
  environment:
    PEPE_WEBHOOK: ${ env:PEPE_WEBHOOK }
    AUDIENCE: ${ env:AUDIENCE }
    USER_PERMISSIONS: ${ env:USER_PERMISSIONS }
    DEV_SGID: ${ env:DEV_SGID }
    QA_SGID: ${ env:QA_SGID }
    PROD_SGID: ${ env:PROD_SGID }
    TOOLS_SGID: ${ env:TOOLS_SGID }
    GLOBAL_IPSET_DYNAMIC: ${ env:GLOBAL_IPSET_DYNAMIC }
    GLOBAL_IPSET_FIXED: ${ env:GLOBAL_IPSET_FIXED }
    REGIONAL_IPSET_DYNAMIC: ${ env:REGIONAL_IPSET_DYNAMIC }
    REGIONAL_IPSET_FIXED: ${ env:REGIONAL_IPSET_FIXED }
  iam:
    role:
      name: pepe-${self:provider.stage}-role
      statements:
        - Effect: 'Allow'
          Action:
            - 'ec2:RevokeSecurityGroupIngress'
            - 'ec2:AuthorizeSecurityGroupIngress'
          Resource:
            - 'arn:aws:ec2:us-east-1:${ env:AWS_ACCOUNT }:security-group/${ env:DEV_SGID }'
            - 'arn:aws:ec2:us-east-1:${ env:AWS_ACCOUNT }:security-group/${ env:QA_SGID }'
            - 'arn:aws:ec2:us-east-1:${ env:AWS_ACCOUNT }:security-group/${ env:PROD_SGID }'
            - 'arn:aws:ec2:us-east-1:${ env:AWS_ACCOUNT }:security-group/${ env:TOOLS_SGID }'
        - Effect: 'Allow'
          Action:
            - 'ec2:DescribeSecurityGroups'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 'waf:GetChangeToken'
            - 'waf:UpdateIPSet'
            - 'waf:GetIPSet'
            - 'waf-regional:GetChangeToken'
            - 'waf-regional:UpdateIPSet'
            - 'waf-regional:GetIPSet'
          Resource:
            - 'arn:aws:waf-regional:us-east-1:${ env:AWS_ACCOUNT }:changetoken/*'
            - 'arn:aws:waf-regional:us-east-1:${ env:AWS_ACCOUNT }:ipset/${ env:REGIONAL_IPSET_DYNAMIC }'
            - 'arn:aws:waf-regional:us-east-1:${ env:AWS_ACCOUNT }:ipset/${ env:REGIONAL_IPSET_FIXED }'
            - 'arn:aws:waf::${ env:AWS_ACCOUNT }:changetoken/*'
            - 'arn:aws:waf::${ env:AWS_ACCOUNT }:ipset/${ env:GLOBAL_IPSET_DYNAMIC }'
            - 'arn:aws:waf::${ env:AWS_ACCOUNT }:ipset/${ env:GLOBAL_IPSET_FIXED }'
  stackTags:
    environment: tools
    duration: indeterminate
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  pepe:
    handler: src/app.handler
    name: ${opt:stage, 'dev'}-pepe-bot
    events:
      - http:
          method: POST
          path: googlechat
      - schedule:
          name: clear-waf-dynamic-ips
          description: Clear all waf dynamic ips
          rate: cron(0 9 1,15 * ? *)
          input:
            resource: 'cloudwatch events'
            user:
              displayName: 'DevOps'
              email: 'devops@boomcredit.net'
            message:
              argumentText: 'clean'
              annotations:
                - slashCommand:
                    commandName: '/iprelease'
              slashCommand:
                commandId: '1'
