service: pepe

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-plugin-resource-tagging

custom:
  wsgi:
    app: src/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-1
  environment:
    GLOBAL_IPSET: ${env:GLOBAL_IPSET}
    REGIONAL_IPSET: ${env:REGIONAL_IPSET}
    AUDIENCE: ${env:AUDIENCE}
  stackTags:
    environment: tools
    duration: temporary

functions:
  pepe:
    handler: wsgi.handler
    events:
      - http: POST /
      - http: 'POST {proxy+}'
