service: pepe

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-resource-tagging

package:
  exclude:
    - ./**
    - '!src/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  memorySize: 128
  timemout: 15
  role: arn:aws:iam::212568053769:role/role-lambda-pepe
  environment:
    USERS: ${env:USERS}
    DEV_SGID: ${env:DEV_SGID}
    QA_SGID: ${env:QA_SGID}
    PROD_SGID: ${env:PROD_SGID}
    TOOLS_SGID: ${env:TOOLS_SGID}
    GLOBAL_IPSET_DYNAMIC: ${env:GLOBAL_IPSET_DYNAMIC}
    GLOBAL_IPSET_FIXED: ${env:GLOBAL_IPSET_FIXED}
    REGIONAL_IPSET_DYNAMIC: ${env:REGIONAL_IPSET_DYNAMIC}
    REGIONAL_IPSET_FIXED: ${env:REGIONAL_IPSET_FIXED}
    AUDIENCE: ${env:AUDIENCE}
  stackTags:
    environment: tools
    duration: indeterminate
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  pepe:
    handler: src/app.handler
    name: ${self:provider.stage}-pepe-bot
    events:
      - http:
          path: /
          method: POST
