name: '[DEV] Pipeline'
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ROLE: ${{ secrets.ROLE }}
      USERS: ${{ secrets.USERS }}
      DEV_SGID: ${{ secrets.DEV_SGID }}
      QA_SGID: ${{ secrets.QA_SGID }}
      PROD_SGID: ${{ secrets.PROD_SGID }}
      TOOLS_SGID: ${{ secrets.TOOLS_SGID }}
      GLOBAL_IPSET_DYNAMIC: ${{ secrets.GLOBAL_IPSET_DYNAMIC }}
      GLOBAL_IPSET_FIXED: ${{ secrets.GLOBAL_IPSET_FIXED }}
      REGIONAL_IPSET_DYNAMIC: ${{ secrets.REGIONAL_IPSET_DYNAMIC }}
      REGIONAL_IPSET_FIXED: ${{ secrets.REGIONAL_IPSET_FIXED }}
      AUDIENCE: ${{ secrets.DEV_AUDIENCE }}
      STAGE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install Serverless Packages
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: npx serverless deploy --stage $STAGE
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: '[DEV] Deploy'
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
