name: "(Pepe) Pipeline"
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GLOBAL_IPSET: ${secrets:GLOBAL_IPSET}
      REGIONAL_IPSET: ${secrets:REGIONAL_IPSET}
      AUDIENCE: ${secrets:AUDIENCE}
      STAGE: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          source scripts.sh
          py-install
      - name: Install Serverless Packages
        run: npm install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: serverless deploy --stage $STAGE
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: Deploy
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
