name: '[PROD] Pipeline'
on:
  push:
    tags: ['v[1-2][0-9].[0-1][0-9].[0-3][0-9]*']
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_URI: s3://boomcredit-devops/pepe/secrets.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download secrets.yml from S3
        run: aws s3 cp $S3_URI ./secrets.yml --region us-east-1
      - name: Deploy
        run: npm run deploy:prod
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        if: always()
        with:
          name: '[PROD] Deploy'
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
